name: 'PR'
description: 'Action to run PR pipeline'
inputs:
  target:
    description: 'target to apply, pr or apply'
    required: true
    default: 'apply'
  repo:
    required: true
    description: 'Name of the repository'
  github_token:
    required: true
    description: 'Github Token'
  working_directory:
    required: true
    description: Where to run the action
    default: '.'
  workload_identity_provider:
    description: 'Workload Identity Provider to access artifactory'
  service_account:
    description: 'Workload Identity SA to access artifactory'

runs:
  using: "composite"
  steps: 
  - name: install
    uses: codimite-devops/cluster-config-gen-action/install@main
  - name: export-env
    uses: codimite-devops/cluster-config-gen-action/export-pr-env@main
  - run: |
      git config --global --add safe.directory '*'
    shell: bash
  - name: git-branch
    working-directory: ${{ inputs.working_directory }}
    shell: bash
    run: |
      export SUBDIR="$PWD"
      echo "git working on: $REPO_URL version $PULL_PULL_REF:$(echo $JOB_NAME | tr '[:lower:]' '[:upper:]')-$PULL_NUMBER@$PULL_PULL_SHA to dir: $SUBDIR"
      git fetch origin $PULL_PULL_REF:$(echo $JOB_NAME | tr '[:lower:]' '[:upper:]')-$PULL_NUMBER
      git checkout $(echo $JOB_NAME | tr '[:lower:]' '[:upper:]')-$PULL_NUMBER
      git reset --hard $PULL_PULL_SHA
      echo "checked out revision: $PULL_PULL_REF:$(echo $JOB_NAME | tr '[:lower:]' '[:upper:]')-$PULL_NUMBER@$PULL_PULL_SHA to dir: $SUBDIR"
  - name: git-merge
    working-directory: ${{ inputs.working_directory }}
    shell: bash
    run: |
      counter=0
      until [ "$counter" -eq 3 ]; do
        # lets avoid git rebase/merge conflicts on promotions
        jx gitops git merge --rebase --merge-arg "-Xtheirs" && exit 0
        counter=$((counter+1))
        git rebase --abort
        if git log -1 --pretty=%B | grep -i regenerate; then
          git reset --hard HEAD~1
        fi
      done
      exit 1
  - id: "auth"
    name: "Authenticate to Google Cloud"
    uses: "google-github-actions/auth@v2"
    with:
      token_format: "access_token"
      workload_identity_provider: ${{ inputs.workload_identity_provider }}
      service_account: ${{ inputs.service_account }}
  - uses: "docker/login-action@v3"
    with:
      registry: "us-central1-docker.pkg.dev" # or
      username: "oauth2accesstoken"
      password: "${{ steps.auth.outputs.access_token }}"
  - name: make-pr
    uses: codimite-devops/cluster-config-gen-action/make@main
    if: github.event_name == 'pull_request'
    with:
      target: pr
      repo: ${{ github.event.repository.name }}
      github_token: ${{ inputs.github_token }}
      working-directory: ${{ inputs.working_directory }}
