name: 'PR'
description: 'Action to run PR pipeline'
inputs:
  target:
    description: 'target to apply, pr or apply'
    required: true
    default: 'apply'
  repo_name:
    required: true
    description: 'Name of the repository'
  github_token:
    required: true
    description: 'Github Token'
  kubectl_apply:
    description: 'type of the repository'
    default: no-kubectl-apply
  working_directory:
    required: true
    description: Where to run the action
    default: '.'
  workload_identity_provider:
    description: 'Workload Identity Provider to access artifactory'
  service_account:
    description: 'Workload Identity SA to access artifactory'
  cluster_project_id:
    description: 'Cluster Project ID'
    default: ""
  cluster_project_location:
    description: 'Cluster Location'
    default: ""
  cluster_name:
    description: 'Cluster Name'
    default: ""

runs:
  using: "composite"
  steps: 
  - name: install
    uses: codimite-devops/cluster-config-gen-action/install@main
  - name: export-env
    uses: codimite-devops/cluster-config-gen-action/export-env@main
  - run: |
      git config --global --add safe.directory '*'
    shell: bash
  - uses: codimite-devops/cluster-config-gen-action/pr-branch@main
  - name: auth
    uses: codimite-devops/cluster-config-gen-action/auth@main
    with:
      workload_identity_provider: ${{ inputs.workload_identity_provider }}
      service_account: ${{ inputs.service_account }}
      cluster_project_id: ${{ inputs.cluster_project_id }}
      cluster_project_location: ${{ inputs.cluster_project_location }}
  - name: make-pr
    uses: codimite-devops/cluster-config-gen-action/make@main
    if: github.event_name == 'pull_request'
    with:
      target: pr
      repo_name: ${{ github.event.repository.name }}
      github_token: ${{ inputs.github_token }}
      working_directory: ${{ inputs.working_directory }}
      kubectl_apply: ${{ inputs.kubectl_apply }}
