name: 'Install'
description: 'Action install packages'


runs:
  using: "composite"
  steps:
  - name: Installing dependencies
    shell: bash
    run: |
      wget https://github.com/helmfile/helmfile/releases/download/v0.163.1/helmfile_0.163.1_linux_amd64.tar.gz
      tar -xzvf helmfile_0.163.1_linux_amd64.tar.gz
      chmod +x helmfile 
      mv helmfile /usr/local/bin/helmfile

      curl -L https://github.com/jenkins-x/jx/releases/download/v3.10.138/jx-linux-amd64.tar.gz | tar xzv
      chmod +x jx 
      mv jx /usr/local/bin
