name: 'Make'
description: 'Action to run Makefile commands'
inputs:
  target:
    description: 'target to apply, pr or apply'
    required: true
    default: 'apply'
  repo_name:
    required: true
    description: 'Name of the repository'
  kubectl_apply:
    description: 'type of the repository'
    default: no-kubectl-apply
  github_token:
    required: true
    description: 'Github Token'
  working_directory:
    required: true
    description: Where to run the action
    default: '.'
  copy_source:
    default: no-copy-source
    description: ''
  gitops_scheduler:
    default:  no-gitops-scheduler
    description: ''
  repository_resolve:
    default:  no-repository-resolve
    description: ''
  gitops_webhook_update:
    default: no-gitops-webhook-update
    description: ''
  helmfile_use_selectors:
    default: "true"
    description: ''

runs:
  using: "composite"
  steps:
    - name: Set GitHub Path
      run: echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
      shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}
    - name: Run Makefile
      run: |
        make ${{ inputs.target }} 
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      env:
        MAKEFILES: '${{ github.action_path }}/Makefile.mk'
        GITHUB_TOKEN: ${{ inputs.github_token }}
        REPO_NAME: ${{ inputs.repo_name }}
        COPY_SOURCE: ${{ inputs.copy_source }}
        GENERATE_SCHEDULER: ${{inputs.gitops_scheduler }}
        REPOSITORY_RESOLVE: ${{ inputs.repository_resolve }}
        GITOPS_WEBHOOK_UPDATE: ${{ inputs.gitops_webhook_update }}
        HELMFILE_USE_SELECTORS: ${{ inputs.helmfile_use_selectors }}
        KUBEAPPLY: ${{ inputs.kubectl_apply }}

