name: 'Make'
description: 'Action to run Makefile commands'
inputs:
  target:
    description: 'target to apply, pr or apply'
    required: true
    default: 'apply'
  repo:
    required: true
    description: 'Name of the repository'
  github-token:
    required: true
    description: 'Github Token'
  working-directory:
    required: true
    description: Where to run the action
    default: '.'
  copy-source:
    default: no-copy-source
    description: ''
  gitops-scheduler:
    default:  no-gitops-scheduler
    description: ''
  repository-resolve:
    default:  no-repository-resolve
    description: ''
  gitops-webhook-update:
    default: no-gitops-webhook-updateb
    description: ''
  helmfile_use_selectors:
    default: "true"
    description: ''

runs:
  using: "composite"
  steps:
    - name: Set GitHub Path
      run: echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
      shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}
    - name: Run Makefile
      run: |
        make ${{ inputs.target }} 
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      env:
        MAKEFILES: '${{ github.action_path }}/Makefile.mk'
        GITHUB_TOKEN: ${{ inputs.github-token }}
        REPO: ${{ inputs.repo }}
        COPY_SOURCE: ${{ inputs.copy-source }}
        GENERATE_SCHEDULER: ${{inputs.gitops-scheduler }}
        REPOSITORY_RESOLVE: ${{ inputs.repository-resolve }}
        GITOPS_WEBHOOK_UPDATE: ${{ inputs.gitops-webhook-update }}
        HELMFILE_USE_SELECTORS: ${{ inputs.helmfile_use_selectors }}

